---
- name: "Restart docker"
  service:
    name: docker
    state: restarted
  listen: "restart docker"

- name: Restart container
  docker_container:
    name: rdo-docker-proxy
    image: rdo-docker-proxy
    state: started
    restart: yes
    #restart_policy: always
  listen: "restart container"