---
- name: "Install pre-requisites"
  apt: pkg={{ item }} state=present
  with_items:
   - docker.io
   - docker
   - python-pip
  notify: "restart docker"

- name: "Install docker-py"
  shell: pip install docker-py

#- name: "Install azure-cli"
#  shell: curl -sL https://aka.ms/InstallAzureCLIDeb | bash

#- name: "Log into Azure"
#  shell: az login --service-principal -u {{ ARM_CLIENT_ID }} -p {{ ARM_CLIENT_SECRET }} --tenant {{ ARM_TENANT_ID }}

- name: "Log into ACR"
  shell: az acr login --name hmctssandbox

- name: "Run rdo-docker-proxy container"
  docker_container:
    name: rdo-docker-proxy
    image: hmctssandbox.azurecr.io/rdo-docker-proxy:master-6c1735c
    hostname: rdo-docker-proxy
    published_ports: 0.0.0.0:8080:3128
    log_driver: syslog

- name: "Container present"
  docker_container:
    name: rdo-docker-proxy
    image: hmctssandbox.azurecr.io/rdo-docker-proxy:master-6c1735c
    state: present
  notify: "restart container"