---
- name: "Install pre-requisites"
  apt: pkg={{ item }} state=present
  with_items:
   - docker.io
   - docker
   - python-pip
  notify: "restart docker"

- name: "Install docker-py"
  shell: pip install docker-py

- name: "Log into ACR"
  shell: az acr login --name hmctssandbox

- name: "Run rdo-docker-proxy container"
  docker_container:
    name: rdo-docker-proxy
    image: hmctssandbox.azurecr.io/rdo-docker-proxy:master-a24b835
    hostname: rdo-docker-proxy
    published_ports: 0.0.0.0:8080:3128
    log_driver: syslog
    volumes:
     - /var/log/rdo-docker-proxy/squid:/var/log
    # - /etc/rdo-docker-proxy/squid:/etc/squid

- name: "Container present"
  docker_container:
    name: rdo-docker-proxy
    image: hmctssandbox.azurecr.io/rdo-docker-proxy:master-a24b835
    state: present
  notify: "restart container"