---
- name: "Install pre-requisites"
  apt: pkg={{ item }} state=present
  with_items:
   - docker.io
   - docker
   - python-pip
  notify: "restart docker"

- name: "Install docker-py"
  shell: pip install docker-py

- name: "Pip Az Cli Install"
  shell: pip install azure-cli

# Testing ig Pip AZ works without this
#- name: "Install azure-cli"
#  shell: curl -sL https://aka.ms/InstallAzureCLIDeb | bash

- name: "Az Login"
  shell: az login --service-principal -u "{{ arm_client_id }}" -p "{{ arm_client_secret }}" --tenant "{{ arm_tenant_id }}"

- name: "Log into ACR"
  shell: az acr login --name hmctssandbox

- name: "Run rdo-docker-proxy container"
  docker_container:
    name: rdo-docker-proxy
    image: hmctssandbox.azurecr.io/rdo-docker-proxy:master-e3db3c9
    hostname: rdo-docker-proxy
    published_ports: 0.0.0.0:8080:8080
    network_mode: host
    log_driver: syslog
    volumes:
     - /var/log/rdo-docker-proxy/squid:/var/log
     - /etc/rdo-docker-proxy/squid:/etc/squid

- name: "Container present"
  docker_container:
    name: rdo-docker-proxy
    image: hmctssandbox.azurecr.io/rdo-docker-proxy:master-e3db3c9
    #hostname: rdo-docker-proxy
    #published_ports: 0.0.0.0:8080:8080
    state: present
  notify: "restart container"
